[package]
name = "stark_curve"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "stark_curve"
path = "src/lib.rs"

[dependencies]
# paritys scale codec locks us here
bitvec = "0.20.4"
ff = { git = "https://github.com/eqlabs/ff", branch = "var_time_eq", default-features = false, features = [
    "derive",
    "alloc",
] }

[dev-dependencies]
pretty_assertions = "1.3.0"
