[package]
name = "pathfinder-serde"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
description = "Starknet-specific serialization utilities for Pathfinder"
repository = "https://github.com/eqlabs/pathfinder"
keywords = ["starknet", "ethereum", "serde", "serialization", "web3"]
categories = [
    "encoding",
    "cryptography::cryptocurrencies",
    "development-tools",
    "web-programming",
]

[dependencies]
anyhow = { workspace = true }
num-bigint = { workspace = true }
pathfinder-common = { version = "0.21.3", path = "../common" }
pathfinder-crypto = { version = "0.21.3", path = "../crypto" }
primitive-types = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_with = { workspace = true }

[dev-dependencies]
pretty_assertions_sorted = { workspace = true }
