[package]
name = "pathfinder-serde"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.62"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
num-bigint = { version = "0.4.3", features = ["serde"] }
pathfinder-common = { path = "../common" }
primitive-types = { version = "0.12.1", features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_with = { workspace = true }
stark_hash = { path = "../stark_hash" }

[dev-dependencies]
pretty_assertions = "1.3.0"
