[package]
name = "pathfinder-storage"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.62"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
base64 = "0.13.1"
bitvec = "0.20.4"
const_format = { workspace = true }
data-encoding = "2.3.3"
fake = { version = "2.5.0", features = ["derive"] }
flate2 = "1.0.25"
hex = "0.4.3"
lazy_static = "1.4.0"
pathfinder-common = { path = "../common" }
pathfinder-ethereum = { path = "../ethereum" }
pathfinder-serde = { path = "../serde" }
primitive-types = "0.12.1"
r2d2 = "0.8.10"
r2d2_sqlite = "0.21.0"
rand = { version = "0.8.5" }
rusqlite = { version = "0.28.0", features = ["bundled", "functions"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["arbitrary_precision", "raw_value"] }
serde_with = { workspace = true }
sha3 = "0.10"
stark_hash = { path = "../stark_hash" }
starknet-gateway-client = { path = "../gateway-client" }
starknet-gateway-types = { path = "../gateway-types" }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
zstd = "0.12"

[dev-dependencies]
assert_matches = { workspace = true }
tempfile = "3.4"
