[package]
name = "pathfinder-storage"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }

[features]
small_aggregate_filters = []

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true, features = ["serde"] }
bitvec = { workspace = true }
bloomfilter = { workspace = true }
cached = { workspace = true }
const_format = { workspace = true }
fake = { workspace = true }
flume = { version = "0.11.0", default-features = false, features = [
    "eventual-fairness",
] }
hex = { workspace = true }
metrics = { workspace = true }
paste = { workspace = true }
pathfinder-casm-hashes = { path = "../casm-hashes" }
pathfinder-class-hash = { path = "../class-hash" }
pathfinder-common = { path = "../common" }
pathfinder-compiler = { path = "../compiler" }
pathfinder-crypto = { path = "../crypto" }
pathfinder-ethereum = { path = "../ethereum" }
pathfinder-serde = { path = "../serde" }
primitive-types = { workspace = true }
r2d2 = { workspace = true }
r2d2_sqlite = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
rusqlite = { workspace = true, features = [
    "bundled",
    "functions",
    "vtab",
    "array",
    "hooks",
] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = [
    "arbitrary_precision",
    "raw_value",
] }
serde_with = { workspace = true }
sha3 = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
util = { path = "../util" }
zstd = { workspace = true, features = ["experimental"] }

[dev-dependencies]
pretty_assertions_sorted = { workspace = true }
rstest = { workspace = true }
test-log = { workspace = true, features = ["trace"] }
tracing-subscriber = { workspace = true }
