[package]
name = "pathfinder-storage"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.62"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
test-utils = []

[dependencies]
anyhow = "1.0.66"
base64 = "0.13.1"
bitvec = "0.20.4"
data-encoding = "2.3.3"
ethers = "1.0.2"
flate2 = "1.0.25"
hex = "0.4.3"
lazy_static = "1.4.0"
pathfinder-common = { path = "../common" }
pathfinder-ethereum = { path = "../ethereum" }
pathfinder-serde = { path = "../serde" }
r2d2 = "0.8.10"
r2d2_sqlite = "0.21.0"
rusqlite = { version = "0.28.0", features = ["bundled", "functions"] }
serde = { version = "1.0.149", features = ["derive"] }
serde_json = { version = "1.0.89", features = ["arbitrary_precision", "raw_value"] }
serde_with = "2.1.0"
sha3 = "0.10"
stark_hash = { path = "../stark_hash" }
starknet-gateway-client = { path = "../gateway-client" }
starknet-gateway-types = { path = "../gateway-types" }
thiserror = "1.0.37"
tokio = { workspace = true }
tracing = "0.1.37"
zstd = "0.12"

[dev-dependencies]
assert_matches = "1.5.0"
# fake = { workspace = true }
# pretty_assertions = "1.3.0"
# stark_hash = { path = "../stark_hash", features = ["test-utils"] }
