[package]
name = "pathfinder-ethereum"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.62"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
pathfinder-common = { path = "../common" }
pathfinder-retry = { path = "../retry" }
stark_hash = { path = "../stark_hash" }
thiserror = { workspace = true }
tokio = { workspace = true }
primitive-types = { version = "0.12.1", features = ["serde"] }
reqwest = { version = "0.11.13", features = ["json"] }
tracing = "0.1.37"
const-decoder = "0.3.0"

[dev-dependencies]
hex = "0.4.3"
pretty_assertions = "1.3.0"
tokio = { workspace = true, features = ["macros"] }
