[package]
name = "pathfinder-ethereum"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.62"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
async-trait = "0.1.52"
ethers = "1.0.0"
futures = { version = "0.3", default-features = false, features = ["std"] }
lazy_static = "1.4.0"
pathfinder-common = { path = "../common" }
pathfinder-retry = { path = "../retry" }
reqwest = { version = "0.11.4", features = ["json"] }
stark_hash = { path = "../stark_hash" }
thiserror = "1.0.30"
tokio = "1.11.0"
tracing = "0.1.31"

[dev-dependencies]
assert_matches = "1.5.0"
hex = "0.4.3"
hex-literal = "0.3"
pretty_assertions = "1.0.0"
tokio = { version = "1.11.0", features = ["macros"] }

[build-dependencies]
ethers = "1.0.0"