[package]
name = "tagged"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }

[dependencies]
fake = { workspace = true, features = ["derive"] }

[dev-dependencies]
pretty_assertions_sorted = { workspace = true }
tagged-debug-derive = { path = "../tagged-debug-derive" }
