[package]
name = "pathfinder-executor"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
blockifier = { workspace = true }
cached = "0.44.0"
cairo-vm = { workspace = true }
lazy_static = { workspace = true }
pathfinder-common = { path = "../common" }
pathfinder-storage = { path = "../storage" }
primitive-types = { workspace = true, features = ["serde"] }
stark_hash = { path = "../stark_hash" }
starknet-gateway-types = { path = "../gateway-types" }
starknet_api = { workspace = true }
tracing = { workspace = true }
