[package]
name = "stark_hash_python"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.73"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "starknet_pathfinder_crypto"
crate-type = ["cdylib"]

[dependencies]
pathfinder-crypto = { path = "../crypto" }
num-bigint = "0.4.4"
pyo3 = { version = "0.17.3", features = ["extension-module", "num-bigint"] }
