# Builds and uploads docker images whenever a version tag is pushed. When a release is created,
# the associated image is then tagged with the version number and latest.

name: Docker

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  release:
    types: [published]

env:
  # Workaround for https://github.com/rust-lang/cargo/issues/8719#issuecomment-1516492970
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  # Build a docker image unless this was triggered by a release.
  build-image:
    if: github.event_name != 'release'
    runs-on: pathfinder-large-ubuntu
    steps:
      - name: Determine Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: eqlabs/pathfinder
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate version
        id: generate_version
        run: |
          echo -n "pathfinder_version=" >> $GITHUB_OUTPUT
          git describe --tags --dirty >> $GITHUB_OUTPUT
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [worker.oci]
              max-parallelism = 4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # Required for git security reasons. See https://github.com/rustyhorde/vergen/pull/126#issuecomment-1201088162
      - name: Vergen git safe directory
        run: git config --global --add safe.directory /workspace
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: |
            linux/amd64
            linux/arm64
          file: ./Dockerfile
          build-args: |
            PATHFINDER_FORCE_VERSION=${{ steps.generate_version.outputs.pathfinder_version }}
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: eqlabs/pathfinder:snapshot-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Add the release labels to the associated docker image.
  tag-release:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Tag image with release name
        run: docker buildx imagetools create -t eqlabs/pathfinder:${{ github.event.release.tag_name }} eqlabs/pathfinder:snapshot-${{ github.sha }}
        # Only tag the image as 'latest' if its a release i.e. not a prerelease.
      - name: Tag image with 'latest'
        if: ${{ !github.event.release.prerelease }}
        run: docker buildx imagetools create -t eqlabs/pathfinder:latest eqlabs/pathfinder:snapshot-${{ github.sha }}
